INSERT INTO images(image_name,location_name, featured_image, vertical)
VALUES 
('fountain_museum_stare.jpg', 'museum','f','f'),
('cricket_city_hall.jpg', 'city hall','f','f'),
('Joey_Onajon_Ziyoda_City_Hall_1.jpg', 'city hall','f','t'),
('Joey_Onajon_Ziyoda_City_Hall_2.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_1.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_2.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_3.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_5.jpg', 'city hall','f','f'),
('Joey_Saida_Ziyoda_City_Hall_1.jpg', 'city hall','f','f'),
('Saida_City_Hall_2.jpg', 'city hall','f','f'),
('Saida_City_Hall_3.jpg', 'city hall','f','f'),
('Saida_City_Hall_4.jpg', 'city hall','f','t'),
('Saida_City_Hall_1.jpg', 'city hall','f','f'),
('Saida_City_Hall_1.jpg', 'city hall','f','f'),
('Daniel_City_Hall_1.jpg', 'city hall','f','f'),
('Joey_Tyron_City_Hall_2.jpg', 'city hall','f','t'),
('Joey_Tyron_Waldo_City _Hall_1.jpg', 'city hall','f','f'),
('Joey_Tyron_Waldo_City_Hall_2.jpg', 'city hall','f','f'),
('Joey_Tyron_Waldo_City_Hall_3.jpg', 'city hall','f','f'),
('Joey_Tyrone_Waldo_City_Hall_4.jpg', 'city hall','f','f'),
('Joey_City_Hall_4.jpg', 'city hall','f','f'),
('Joey_Tyron_City_Hall_1.jpg', 'city hall','f','t'),
('Cricket_City_Hall_2.jpg', 'city hall','f','t'),
('Cricket_City_hall_3.jpg', 'city hall','f','t'),
('Joey_City_Hall_2.jpg', 'city hall','t','t'),
('Joey_City_Hall_3.jpg', 'city hall','f','t'),
('Joey_Cricket_city_hall_1.jpg', 'city hall','f','t'),
('Joey_Cricket_City_Hall_3.jpg', 'city hall', 't','t'),
('Joey_Daniel_city_hall_2.jpg', 'city hall','f','t'),
('Tyron_Cricket_Joey_Daniel_City_Hall.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_6.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_8.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_9.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_10.jpg', 'city hall','f','f'),
('Joey_Saida_CIty_Hall_11.jpg', 'city hall','f','f'),
('Joey_Saida_CIty_Hall_12.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_13.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall.jpg', 'city hall','f','t'),
('Joey_Saida_Onajon_Cricket_City_Hall_1.jpg', 'city hall','f','f'),
('Joey_Saida_Tyrone_City_Hall_1.jpg', 'city hall','f','t'),
('Joey_Saida_Tyrone_Cricket_Scott_City_Hall_1.jpg', 'city hall','f','f'),
('Joey_Saida_Ziyoda_City_Hall_2.jpg', 'city hall','f','f'),
('Joey_Saida_Ziyoda_City_Hall_2 copy.jpg', 'city hall','f','f'),
('Joey_Saida_Ziyoda_City_Hall_2.jpg', 'city hall','f','f'),
('MJ_Ziyoda_City_Hall_1.jpg', 'city hall','f','f'),
('Onajaon_Dilobar_Umid_Ziyoda_Ulugbek_City_Hall_1.jpg', 'city hall','f','f'),
('Pam_Ziyoda_City_Hall_1.jpg', 'city hall','f','f'),
('Pam_Ziyoda_City_Hall_2.jpg', 'city hall','f','f'),
('Pam_Ziyoda_City_Hall_3.jpg', 'city hall','f','t'),
('Saida_Dilobar_MJ_Pam_Ziyoda_Ciry_Hall_1.jpg', 'city hall','f','t'),
('Saida_Dilobar_Onajon_Cricket_Ulugbek.jpg', 'city hall','f','f'),
('Saida_Joey_Onajon_Cricket_Umid_Dilobar_Scott_Bailey_Ziyoda_City_Hall_1.jpg', 'city hall','f','f'),
('Dilobar_MJ_Pam_City_Hall_Court_1.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_1.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_Court_2.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_3.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_4.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_5.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_6.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_7.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_8.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Group_1.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Group_2.jpg', 'city hall','f','f'),
('Joey_Saida_Dilobar_MJ_Pam_Ziyoda_1.jpg', 'city hall','f','f'),
('Joey_Saida_Dilobar_MJ_Pam_Ziyoda_City_Hall_2.jpg', 'city hall','f','f'),
('Joey_Saida_Ziyoda_City_Hall_Court_1.jpg', 'city hall','f','f'),
('Joey_Scott_Ziyoda_City_Hall_Court_1.jpg', 'city hall','f','t'),
('MJ_Daniel_John_Cricket_Umid_City_Hall_1.jpg', 'city hall','f','f'),
('Pam_Ziyoda_City_Hall_4.jpg', 'city hall','f','f'),
('Saida_City_Hall_Court_1.jpg', 'city hall','f','t'),
('Saida_City_Hall_Court_2.jpg', 'city hall','f','t'),
('Saida_City_Hall_Court_3.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_Court_11.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_12.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Court_Group_1.jpg', 'city hall','f','t'),
('Joey_Saida_City_Hall_Group_3.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Group_4.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Group_5.jpg', 'city hall','f','f'),
('Joey_Saida_City_Hall_Kryssy_Tiffany_City_Hall_Court_1.jpg', 'city hall','f','f'),
('Joey_Saida_Cricket_City_Hall_2.jpg', 'city hall','f','t'),
('Joey_Saida_Kryssy_City_Hall_Court_1.jpg', 'city hall','f','t'),
('Joey_Saida_Kryssy_City_Hall_Court_2.jpg', 'city hall','f','t'),
('Joey_Saida_Kryssy_Tiffany_City_Hall_Court_2.jpg', 'city hall','f','f'),
('Joey_Saida_Onajaon_City_Hall_Court_13.jpg', 'city hall','f','f'),
('Joey_Saida_Scott_City_Hall_1.jpg', 'city hall','f','f'),
('Joey_Saida_Tiffany_City_Hall_Court_14.jpg', 'city hall','f','f'),
('Joey_Saida_Tiffany_City_Hall_Court_14.jpg', 'city hall','f','f'),
('Joey_Ziyoda_City_Hall_Court_2.jpg', 'city hall','f','f'),
('Joey_Ziyoda_City_Hall_Court_3.jpg', 'city hall','f','f'),
('Joey_Ziyoda_John_Onajon_City_Hall_Court_1.jpg', 'city hall','f','f'),
('Saida_Daniel_City_Hall_Court.jpg', 'city hall','f','f'),
('Saida_Kryssy_City_Hall_Court_1.jpg', 'city hall','f','f'),
('Joey_Kenny_Joban_City_Hall_1.jpg', 'city hall','f','f'),
('Joey_Kenny_Joban_City_Hall_2.jpg', 'city hall','t','f'),
('Joey_Saida_City_Hall_Group_6.jpg', 'city hall','f','f'),
('Joey_Saida_Cricket_City_Hall_3.jpg', 'city hall','f','f'),
('Joey_Saida_Cricket_Onajonim_City_Hall_2.jpg', 'city hall','f','f'),
('Saida_Ziyoda_City_Hall_1.jpg', 'city hall','f','t'),
('Cricket_Boat_1.jpg', 'boat','f','t'),
('Cricket_Boat_2.jpg', 'boat','f','t'),
('Cricket_Boat_3.jpg', 'boat', 't','t'), 
('Cricket_Boat_4.jpg', 'boat','f','t'),
('Cricket_Boat_5.jpg', 'boat','f','t'),
('Dilobar_Onajon_Boat_1.jpg', 'boat','f','f'),
('Dilobar_Onajon_Boat_1.jpg', 'boat','f','f'),
('Dilobar_Onajon_Boat_2.jpg', 'boat','f','f'),
('Joey_Saida_Cricket_Tyrone_Joban_Ziyoda_2.jpg', 'boat','f','f'),
('Joey_Saida_Cricket_Tyrone_Joban_Ziyoda_Boat_1.jpg', 'boat','f','f'),
('Joey_Saida_Ziyoda_Boat_1.jpg', 'boat','f','f'),
('Joey_Saida_Ziyoda_Boat_2.jpg', 'boat','f','f'),
('Joey_Saida_Ziyoda_Boat_3.jpg', 'boat','f','f'),
('John_MJ_Boat_1.jpg', 'boat','f','t'),
('John_MJ_Boat_2.jpg', 'boat','f','f'),
('Kenny_Kryssy_Bailey_Scott_Boat_1.jpg', 'boat','f','f'),
('Onajon_Boat_1.jpg', 'boat','f','f'),
('Onajon_Boat_2.jpg', 'boat','f','f'),
('Onajon_Jasur_Boat_1.jpg', 'boat','f','f'),
('Tiffany_Boat_1.jpg', 'boat','f','t'),
('Allison_Central Park_1.jpg', 'Central Park','f','f'),
('Jasur_Boat_1.jpg', 'boat','f','t'),
('Jasur_Boat_2.jpg', 'boat','f','t'),
('Joey_Saida_Central_Park_13.jpg', 'Central Park', 't','f'),
('Joey_Saida_Central_Park_14.jpg', 'Central Park', 't','f'),
('Joey_Saida_Central_Park_15.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_16.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_17', 'Central Park','f','f'),
('Joey_Saida_Central_Park_18.jpg', 'Central Park', 't','t'),
('Joey_Saida_Central_Park_19.jpg', 'Central Park','f','f'),
('Tiffany_Joban_Boat_1.jpg', 'Central Park','f','t'),
('Tiffany_Joban_Boat_2.jpg', 'Central Park','f','t'),
('Tiffany_Joban_Boat_3.jpg', 'Central Park','f','t'),
('Tyrone_Princie_Boat.jpg', 'Central Park','f','f'),
('Ulugbek_Boat_1.jpg', 'boat','f','f'),
('Ulugbek_Boat_2.jpg', 'boat','f','f'),
('Umid_Dilobar_Pam_Ziyoda_Ulubek_Boat_1.jpg', 'boat','f','f'),
('Umid_Dilobar_Pam_Ziyoda_Ulubek_Boat_1 copy.jpg', 'boat','f','f'),
('Umid_Dilobar_Pam_Ziyoda_Ulubek_Boat_2.jpg', 'boat','f','f'),
('Joey_Saida_Central_Park_20.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_21.jpg', 'Central Park','f','f'),
('Joey_Saida_Cricket_Central_Park_1.jpg', 'Central Park','f','f'),
('Cricket_Kryssy_Central_Park.jpg', 'Central Park','f','f'),
('Cricket_Tiffany_Central_Park.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_1.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_3.jpg', 'Central Park', 't','f'),
('Joey_Saida_Central_Park_4.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_5.jpg', 'Central Park','t','t'),
('Joey_Saida_Central_Park_6.jpg', 'Central Park', 't','t'),
('Joey_Saida_Central_Park_7.jpg', 'Central Park','f','t'),
('Joey_Saida_Central_Park_8.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_9.jpg', 'Central Park', 't','f'),
('Joey_Saida_Central_Park_10.jpg', 'Central Park', 't','t'),
('Joey_Saida_Cricket_Dilobar_Waldo_Central_Park_1.jpg', 'Central Park','f','f'),
('Joey_Saida_Ziyoda_Central_Park_2.jpg', 'Central Park','f','f'),
('Kryssy_Allison_Boat.jpg', 'boat','f','f'),
('Kryssy_Central_Park_1.jpg', 'Central Park','f','f'),
('Kryssy_Central_PArk_2.jpg', 'Central Park','f','f'),
('MJ_Pam_Boat.jpg', 'boat','f','f'),
('Ziyoda_Central_Park.jpg', 'Central Park','f','f'),
('Joey_Saida_Central_Park_11.jpg', 'Central Park','f','t'),
('Joey_Saida_Central_Park_12.jpg', 'Central Park', 't','t'),
('Saida_Central Park_1.jpg', 'Central Park','f','t'),
('Joey_Sada_Museum_16.jpg', 'Museum', 't','t'),
('Joey_Saida_Museum_2.jpg', 'Museum','f','t'),
('Joey_Saida_Museum_3.jpg', 'Museum','f','t'),
('Joey_Saida_Museum_4.jpg', 'Museum','f','f'),
('Joey_Saida_Museum_5.jpg', 'Museum','f','f'),
('Joey_Saida_Museum_6.jpg', 'Museum','f','f'),
('Joey_Saida_Museum_7.jpg', 'Museum','f','t'),
('Joey_Saida_Museum_8.jpg', 'Museum','f','t'),
('Joey_Saida_Museum_9.jpg', 'Museum','f','f'),
('Joey_Saida_Museum_10.jpg', 'Museum','f','t'),
('Joey_Saida_Museum_11.jpg', 'Museum','f','t'),
('Joey_Saida_Museum_12.jpg', 'Museum','f','t'),
('Saida_Cricket_Kryssy_Tyrone_Kenny_Central_Park.jpg', 'Central Park','f','f'),
('Saida_flowers_Central_Park.jpg', 'Central Park','f','t'),
('Group_Pic_Party_Bus_1.jpg', 'Party Bus','f','f'),
('Group_Pic_Party_Bus_2.jpg', 'Party Bus','f','f'),
('Joey_Kenny_Joban_City_Hall_1.jpg', 'City Hall','f','f'),
('Joey_Kenny_Joban_City_Hall_2.jpg', 'City Hall','f','f'),
('cake_boat1.jpg', 'boat','f','f'),
('cake_boat2.jpg', 'boat','f','f'),
('cake_boat3.jpg', 'boat','f','f'),
('cake_boat4.jpg', 'boat','f','f'),
('city_sunset.jpg', 'boat','f','f'),
('cricket_boat1.jpg', 'boat','f','t'),
('dilobar_boat1.jpg', 'boat','f','f'),
('dilobar_ziyoda_umid_ulugbek_boat1.jpg', 'boat','f','f'),
('dilobar_ziyoda_umid_ulugbek_boat2.jpg', 'boat', 't','f'),
('dilobar_ziyoda_umid_ulugbek_boat3.jpg', 'boat','f','f'),
('group_boat1.jpg', 'boat','f','f'),
('group_boat2.jpg', 'boat','t','f'),
('group_boat4.jpg', 'boat','f','f'),
('group_boat5.jpg', 'boat','f','f'),
('group_boat6.jpg', 'boat','f','f'),
('group_boat7.jpg', 'boat','f','f'),
('group_boat8.jpg', 'boat','f','f'),
('group_boat9.jpg', 'boat','f','f'),
('group_boat10.jpg', 'boat', 't','f'),
('group_sunset_boat1.jpg', 'boat', 't','f'),
('group_sunset_boat2.jpg', 'boat','f','f'),
('group_sunset_boat3.jpg', 'boat','f','f'),
('jasur_boat1.jpg', 'boat','f','f'),
('joban_kenny_kryssy_bailey_scott_boat1.jpg', 'boat','f','f'),
('joban_kenny_kryssy_bailey_scott_boat2.jpg', 'boat','f','f'),
('joban_tiff_boat1.jpg', 'boat','f','f'),
('joban_waldo_boat1.jpg', 'boat','f','f'),
('joey_saida_boat1.jpg', 'boat', 't','f'),
('joey_saida_boat2.jpg', 'boat','f','f'),
('joey_saida_boat3.jpg', 'boat','f','f'),
('joey_saida_boat4.jpg', 'boat','f','f'),
('joey_saida_boat5.jpg', 'boat','f','f'),
('joey_saida_boat7.jpg', 'boat','f','f'),
('joey_saida_boat8.jpg', 'boat','f','f'),
('joey_saida_boat9.jpg', 'boat','f','t'),
('joey_saida_boat10.jpg', 'boat','f','t'),
('joey_saida_boat11.jpg', 'boat','f','t'),
('joey_saida_boat12.jpg', 'boat','f','f'),
('joey_saida_boat13.jpg', 'boat', 't','f'),
('joey_saida_boat14.jpg', 'boat','f','f'),
('joey_saida_boat15.jpg', 'boat', 't','f'),
('joey_saida_boat16.jpg', 'boat', 't','t'),
('joey_saida_boat17.jpg', 'boat','f','t'),
('joey_saida_boat18.jpg', 'boat','f','f'),
('joey_saida_boat19.jpg', 'boat','f','f'),
('joey_saida_boat20.jpg', 'boat','f','f'),
('joey_saida_boat23.jpg', 'boat', 't','f'),
('joey_saida_boat24.jpg', 'boat','f','f'),
('joey_saida_boat25.jpg', 'boat','f','t'),
('joey_saida_boat26.jpg', 'boat','f','t'),
('joey_saida_boat28.jpg', 'boat', 't','f'),
('joey_saida_boat29.jpg', 'boat','f','f'),
('joey_saida_boat30.jpg', 'boat','f','f'),
('joey_saida_boat31.jpg', 'boat','f','f'),
('joey_saida_boat32.jpg', 'boat', 't','f'),
('joey_saida_boat33.jpg', 'boat','f','f'),
('joey_saida_boat34.jpg', 'boat', 't','f'),
('joey_saida_boat35.jpg', 'boat','f','f'),
('joey_saida_boat36.jpg', 'boat','f','f'),
('joey_saida_cricket_boat1.jpg', 'boat','f','f'),
('joey_saida_cricket_ziyoda_boat1.jpg', 'boat','f','f'),
('joey_saida_cricket_ziyoda_boat2.jpg', 'boat','f','f'),
('joey_saida_princie_cricket_tyrone_boat1.jpg', 'boat','f','f'),
('joey_saida_princie_cricket_tyrone_boat2.jpg', 'boat','f','f'),
('joey_saida_ziyoda_boat1.jpg', 'boat','f','f'),
('joey_saida_ziyoda_boat2.jpg', 'boat','f','f'),
('joey_saida_ziyoda_boat3.jpg', 'boat','f','f'),
('joey_saida_ziyoda_princie_boat1.jpg', 'boat','f','t'),
('joey_ziyoda_boat1.jpg', 'boat','f','f'),
('joey_ziyoda_boat2.jpg', 'boat','f','f'),
('joey_ziyoda_kryssy_boat1.jpg', 'boat','f','f'),
('joey_ziyoda_kryssy_boat2.jpg', 'boat','f','f'),
('john_boat1.jpg', 'boat','f','t'),
('kenny_kryssy_boat2.jpg', 'boat','f','t'),
('kryssy_boat1.jpg', 'boat','f','t'),
('kryssy_kenny_boat1.jpg', 'boat','f','t'),
('mj_boat1.jpg', 'boat','f','f'),
('mj_john_boat1.jpg', 'boat','f','f'),
('mj_john_boat2.jpg', 'boat','f','f'),
('onajon_boat1.jpg', 'boat','f','f'),
('princie_boat1.jpg', 'boat','f','f'),
('princie_boat2.jpg', 'boat','f','f'),
('princie_boat3.jpg', 'boat','f','f'),
('princie_cricket_boat1.jpg', 'boat','f','f'),
('princie_cricket_boat2.jpg', 'boat','f','f'),
('princie_cricket_boat4.jpg', 'boat','f','f'),
('raj_waldo_danielle_boat1.jpg', 'boat','f','f'),
('raj_waldo_danielle_boat2.jpg', 'boat','f','f'),
('raj_waldo_danielle_boat3.jpg', 'boat','f','f'),
('saida_kryssy_cricket_boat1.jpg', 'boat','f','f'),
('saida_princie_cricket_tyrone_boat1.jpg', 'boat','f','f'),
('saida_princie_cricket_tyrone_boat2.jpg', 'boat','f','f'),
('saida_princie_cricket_tyrone_tiff_boat1.jpg', 'boat','f','f'),
('statue_of_liberty2.jpg', 'boat','f','f'),
('tiff_bailey_boat1.jpg', 'boat','f','f'),
('tiff_scott_bailey_kryssy_allison_boat1.jpg', 'boat','f','f'),
('tiff_scott_bailey_kryssy_boat1.jpg', 'boat','f','f'),
('tyrone_boat1.jpg', 'boat','f','f'),
('tyrone_boat2.jpg', 'boat','f','f'),
('tyrone_tiff_boat1.jpg', 'boat','f','f'),
('tyrone_tiff_boat2.jpg', 'boat','f','f'),
('tyrone_tiff_boat3.jpg', 'boat','f','f'),
('umid_dilobar_boat1.jpg', 'boat','f','f'),
('umid_ziyoda_boat1.jpg', 'boat','f','f'),
('umid_ziyoda_boat2.jpg', 'boat','f','f'),
('ziyoda_boat1.jpg', 'boat','f','f'),
('ziyoda_boat2.jpg', 'boat','f','f');


-- Joey_City_Hall_4.jpg, Cricket_City_Hall_1.jpg, Joey_Saida_Museum_1.jpg, Joey_Saida_Museum_13.jpg, Joey_Saida_Museum_14.jpg, Joey_Saida_Museum_15.jpg, Joey_Saida_Museum_16.jpg, Joey_Saida_Museum_17.jpg, Joey_Saida_Museum_18.jpg, Saida_City_Hall.jpg, untitled-215.jpg, untitled-216.jpg, untitled.jpg